### ISSUE TITLE
How to clear input box after user selects value

### ISSUE THREAD

**Issue by amnevins** [mizzao/meteor-autocomplete#104]
I am using your package and love it.  Users can select their favorite brands, and upon selection I add them to the users favorites.  However, the box remains filled with the brand name they just selected and they have to delete the name to add another.  Is there an easy way to immediately set the boxes value back to blank after they select it from the drop down?  I appreciate the help, thanks for the awesome work!

Template.favorites.events({
    "autocompleteselect input": function(event, template, doc) {
        //console.log("selected ", doc);

        var brandAlliance = {

            Name: doc.Name,
            Id: doc.Id,
            IconImageUrl: doc.IconImageUrl,
            LandingPageUrl: doc.LandingPageUrl

        };
        //console.log(brandAlliance);

        Meteor.call("brandAddAlliance", brandAlliance);
});

**Comment by Assios** [comment]
Just add an ID to the input field, e.g. like this: 
```
{> inputAutocomplete settings=settings class="form-control" id="auto-input"}}
```
and then call
```
document.getElementById('auto-input').value = '';
```
whenever you want to clear the input box.

**Comment by amnevins** [comment]
Thanks for answering !
