### ISSUE TITLE
Set input as required field

### ISSUE THREAD

**Issue by JacobPariseau** [mizzao/meteor-autocomplete#123]
Is there any way to force the input to set the required=true attribute? I'm doing some fancy CSS for a placeholder but I need to be able to test input:valid to see if there is content inside. Without [required], a blank input will come up as valid and there is no other way in CSS to do this.

**Comment by mizzao** [comment]
Yeah, just add `required=true` to the helper.

**Comment by JacobPariseau** [comment]
I apologize for leaving this thread open: `required=true` solved the issue.
