### ISSUE TITLE
http://autocomplete.meteor.com isn't working?

### ISSUE THREAD

**Issue by robertross** [mizzao/meteor-autocomplete#127]

**Comment by robertross** [comment]
Like almost every other appname.meteor.com link on Atmosphere... How come?

**Comment by mizzao** [comment]
https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308

Although I do have a galaxy credit for this app, I just haven't gotten around to re-submitting it yet. Will do that soon!

**Comment by robertross** [comment]
@mizzao Ah thanks. Good work. I feel it reflects poorly on Meteor, rather than yourself. So many sites aren't working that it feels like Galaxy has fallen over.
