### ISSUE TITLE
retrive docuemnts on spcefic condition

### ISSUE THREAD

**Issue by ketankulkarni** [mizzao/meteor-autocomplete#137]
i have mizzao:autocomplete and mizzao:user status packeges
i want to retrive documents whoes online status is true
javascript code-
settings : function() {
        return {
            position: 'top',
            limit: 2,
            rules: [
                {
                    collection: Meteor.users,
                    field: 'username',
                    token:'@',
                    matchAll: true,
                    template: Template.titles,
                }
            ]
        };
    }

**Comment by mizzao** [comment]
Sorry, GitHub issues are meant for bug reports and feature suggestions, not general support. You may be able to find help for your issue on [StackOverflow](http://stackoverflow.com/).
