### ISSUE TITLE
trigger events instead of using callbacks

### ISSUE THREAD

**Issue by Neobii** [mizzao/meteor-autocomplete#48]
Trigger a `onSelectedMatch` or `onSelectedNoMatch` event.

This way we can use helpers like this:
```javascript
Template.formWithAutocomplete.events({
"onSelectedMatch" : function(e, t, doc){},
"onSelectedNoMatch" : funtion(e, t, doc){}
})
```

**Comment by mizzao** [comment]
I released this in the most recent version, but didn't see a clean way to implement a `noMatch` event. If that's important, let's talk about it and see what we can do.

**Comment by tveeger** [comment]
can you write me an example of how to use this event?

**Comment by mizzao** [comment]
I already have! See https://github.com/mizzao/meteor-autocomplete/blob/master/examples/pubsublocal/client/client.js#L36
