### ISSUE TITLE
Callback is not called on touch event

### ISSUE THREAD

**Issue by ernestorocha** [mizzao/meteor-autocomplete#68]
I'm not sure the best way to solve this, but recently I just discovered that the Meteor ``click`` event (actually jQuery) is not triggered on touch. So, for now, I'm solving this by adding the ``touchend`` event to the same element.

I can do a PR adding this event, but I would like to know if someone has a better solution.

**Comment by mizzao** [comment]
I've implemented the selection using jQuery events instead of callbacks now.

What was the problem here? Is it that the selection doesn't happen, or the callback is not triggered on a selection?

**Comment by ernestorocha** [comment]
I think the problem was that callback wasn't triggered. 

Anyway, now it seems you solved the problem this way. I removed the ``touchend`` event and the autocomplete is still working! Thanks.

**Comment by mizzao** [comment]
I don't think that I solved anything, it must have been Meteor upgraded something to support touch events as clicks.
