### ISSUE TITLE
position: "top" doesn't work when using tokenless completion

### ISSUE THREAD

**Issue by jfly** [mizzao/meteor-autocomplete#75]
It's pretty clear that this was intentional, as there's a comment right here: https://github.com/mizzao/meteor-autocomplete/blob/master/autocomplete-client.coffee#L306 saying "# TODO allow this to render top as well, and possibly used in textareas?"

Are there plans to add support for this this? I was able to monkeypatch a fix locally, but could create a pull request if you like.

**Comment by mizzao** [comment]
Sure, why don't you share what you did for the monkey patch and I'll try and work it in.

**Comment by jfly** [comment]
Here's my monkeypatch ([source](https://github.com/jfly/ccm/blob/master/client/expandableListWithAutocomplete.js#L64)):

```javascript
// Hacky workaround for https://github.com/mizzao/meteor-autocomplete/issues/75
function isWholeField() {
  return true;
}
AutoComplete.prototype.positionContainer = function() {
  var offset, pos, position, rule;
  position = this.$element.position();
  rule = this.matchedRule();
  if((rule !== null) && isWholeField(rule)) {
    pos = {
      left: position.left,
      //JFLY top: position.top + this.$element.outerHeight(),
      width: this.$element.outerWidth()
    };
    //JFLY
    offset = { top: 0 };
    if(this.position === "top") {
      pos.bottom = this.$element.offsetParent().height() - position.top - offset.top;
    } else {
      pos.top = position.top + offset.top + parseInt(this.$element.css('font-size'));
    }
    //JFLY
  } else {
    offset = getCaretCoordinates(this.element, this.element.selectionStart);
    pos = {
      left: position.left + offset.left,
    };
    if(this.position === "top") {
      pos.bottom = this.$element.offsetParent().height() - position.top - offset.top;
    } else {
      pos.top = position.top + offset.top + parseInt(this.$element.css('font-size'));
    }
  }
  return this.tmplInst.$(".-autocomplete-container").css(pos);
};
```

**Comment by mizzao** [comment]
I see, you just copied the stuff from the bottom. Does that actually work properly?

**Comment by jfly** [comment]
It seems to =)

**Comment by mizzao** [comment]
Great, released in 0.5.1.

**Comment by jfly** [comment]
Just tried out 0.5.1, it works, but the position of the dropdown (ok, dropup =)) is a bit weird. Note how in my hack, I was hardcoding `offset = { top: 0 }` ([source](https://github.com/jfly/ccm/blob/master/client/expandableListWithAutocomplete.js#L79)), whereas in 0.5.1, [offset.top is nonzero](https://github.com/mizzao/meteor-autocomplete/commit/141c40ea43ec685122d445e9a85fdd958361baed#diff-0d59505b3bc2f671abcd45abffe67a0eR324). With a nonzero `offset.top`, I'm seeing the dropup overlap a bit with my input field.

**Comment by jfly** [comment]
Any update here? I'm not wild about how things look as of 0.5.1

**Comment by jfly** [comment]
Bump =)

**Comment by mizzao** [comment]
Sorry, things are a little busy here. I went that way because it was just cleaner code. Otherwise it's asymmetric - the dropup doesn't overlap with the top of the box, but the dropdown does for a textarea. I can think about how to make this better later, but maybe you should just go ahead and put your preference into your own fork for now, and just use that.

**Comment by jfly** [comment]
Ah, I see. I didn't realize this was intentional. I do think things look better if the textbox doesn't get overlapped, but I don't feel strongly enough about this to maintain a fork. Thanks!
