### ISSUE TITLE
Default styling + bootstrap leaves unselected options invisible

### ISSUE THREAD

**Issue by tlianza** [mizzao/meteor-autocomplete#76]
Out of the box, with bootstrap3 and no other styles, the items in the dropdown that are not highlighted are invisible for me.  I'm assuming white-on-white, but I can't really tell because when I'm using the chrome inspector, the act of trying to inspect them makes them disappear from the DOM.  I tried overriding the styles of .-autocomplete-item so the default color is black, but that didn't seem to help.  I feel like I'm missing something and would appreciate any pointers in the right direction.

Would be great if the README had some tips on styling.

![screen shot 2015-02-15 at 1 12 18 pm](https://cloud.githubusercontent.com/assets/18635/6205032/d7564668-b514-11e4-9b0c-406a29d0671b.png)

**Comment by mizzao** [comment]
Bootstrap's `label` class, among others, applies this "bold white" text style. You can fix this by looking at your DOM tree and seeing what parent elements have classes that activate this, and taking the autocomplete box out of that element.

You can also debug this by [pausing the browser using a keyboard shortcut](http://superuser.com/q/249050/32370).

**Comment by tlianza** [comment]
Perfect - thank you! The debug tip is extremely helpful.
