### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by Ronald3wing** [mizzao/meteor-autocomplete#98]
16:13:47.175 Exception in defer callback: DOMRange.prototype.$@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:697:1
Blaze.TemplateInstance.prototype.$@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3331:10
AutoComplete.prototype.positionContainer@http://localhost:3000/packages/mizzao_autocomplete.js?328dd83da18e78193b4c7818b33b47d1067e7c41:505:12
AutoComplete.prototype.isShowing/</<@http://localhost:3000/packages/mizzao_autocomplete.js?328dd83da18e78193b4c7818b33b47d1067e7c41:414:11
.withValue@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:955:17
withoutInvocation/<@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:435:26
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:17
onGlobalMessage@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:372:11
1 meteor.js:888:11

**Comment by mizzao** [comment]
Sorry, but this provides no context for the error, nor does it show any apparent effort into finding out what went wrong.
